#!/usr/bin/env python3
"""Generate repo-local tontester Python TL bindings into an audit workdir."""

from __future__ import annotations

import argparse
import importlib
import sys
from pathlib import Path


SCHEMAS = ("lite_api.tl", "ton_api.tl", "tonlib_api.tl")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--repo-root", required=True)
    parser.add_argument("--output-root", required=True)
    args = parser.parse_args()

    repo_root = Path(args.repo_root).resolve()
    output_root = Path(args.output_root).resolve()
    tontester_src = repo_root / "test" / "tontester" / "src"
    schemas_root = repo_root / "tl" / "generate" / "scheme"
    tonapi_dir = output_root / "tonapi"

    missing = [str(schemas_root / name) for name in SCHEMAS if not (schemas_root / name).is_file()]
    if missing:
        print("FORMAT FNSERVE_TOPOLOGY_BLOCKED")
        print("exact reason: missing TL schemas: " + ", ".join(missing))
        print("exact missing repo capability: repo-local tonapi Python binding generation")
        print("whether this parks or closes FNSERVE-MASTER-01: parked")
        return 2
    if not (tontester_src / "tl" / "gen.py").is_file():
        print("FORMAT FNSERVE_TOPOLOGY_BLOCKED")
        print(f"exact reason: missing tontester TL generator at {tontester_src / 'tl' / 'gen.py'}")
        print("exact missing repo capability: repo-local tonapi Python binding generation")
        print("whether this parks or closes FNSERVE-MASTER-01: parked")
        return 2

    sys.path.insert(0, str(tontester_src))
    import tl  # type: ignore

    tonapi_dir.mkdir(parents=True, exist_ok=True)
    (tonapi_dir / "__init__.py").write_text(
        "# Generated by audit/fnserve_master_01_topology/ensure_tonapi.py\n", encoding="utf-8"
    )
    for schema_name in SCHEMAS:
        tl.generate(schemas_root / schema_name, tonapi_dir)

    sys.path.insert(0, str(output_root))
    importlib.invalidate_caches()
    from tonapi import ton_api, tonlib_api  # noqa: F401
    from tontester.install import Install  # noqa: F401

    print("FORMAT FNSERVE_TOPOLOGY_READY")
    print(f"tonapi_path={tonapi_dir}")
    print(f"pythonpath_prefix={output_root}:{tontester_src}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
