#!/usr/bin/env bash
set -euo pipefail

# FNSERVE-MASTER-01 private topology setup/discovery helper.
# This script never sends PoC traffic. It only starts or reuses a local private
# validator-engine topology and emits the environment consumed by
# audit/run_fnserve_master_01_local.sh.

FNSERVE_TOPOLOGY_WORKDIR="${FNSERVE_TOPOLOGY_WORKDIR:-$HOME/ton-fnserve-master-01-topology}"
FNSERVE_TOPOLOGY_MODE="${FNSERVE_TOPOLOGY_MODE:-plan}"   # plan | start | reuse | extract
FNSERVE_TOPOLOGY_MAX_SECONDS="${FNSERVE_TOPOLOGY_MAX_SECONDS:-900}"
FNSERVE_TOPOLOGY_WAIT_SECONDS="${FNSERVE_TOPOLOGY_WAIT_SECONDS:-90}"
FNSERVE_MASTER_HOST="${FNSERVE_MASTER_HOST:-127.0.0.1}"
FNSERVE_MASTER_PORT="${FNSERVE_MASTER_PORT:-30201}"
FNSERVE_BUILD_DIR="${FNSERVE_BUILD_DIR:-}"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"
LOG_DIR="${FNSERVE_TOPOLOGY_WORKDIR}/logs"
ENV_DIR="${FNSERVE_TOPOLOGY_WORKDIR}/env"
RUN_DIR="${FNSERVE_TOPOLOGY_WORKDIR}/run"
TOPOLOGY_DIR="${FNSERVE_TOPOLOGY_WORKDIR}/tontester-topology"
PY_ROOT="${FNSERVE_TOPOLOGY_WORKDIR}/python"
TONAPI_DIR="${PY_ROOT}/tonapi"
ENV_FILE="${ENV_DIR}/fnserve_master_01.env"
PID_FILE="${RUN_DIR}/topology.pid"
HARNESS_FILE="${RUN_DIR}/fnserve_master_topology_harness.py"
IMPORT_CHECK_LOG="${LOG_DIR}/python_import_check.log"

mkdir -p "${LOG_DIR}" "${ENV_DIR}" "${RUN_DIR}"

log() { printf '[fnserve-topology] %s\n' "$*"; }
fail() {
  printf 'FORMAT FNSERVE_TOPOLOGY_BLOCKED\n'
  printf 'exact reason: %s\n' "$*"
  printf 'exact missing repo capability: no resolved local/private full-node-master topology env was produced\n'
  printf 'whether this parks or closes FNSERVE-MASTER-01: parked / BLOCKER_LOCAL_TOPOLOGY / not report-ready\n'
  exit 2
}

is_private_host() {
  case "$1" in
    127.*|localhost|::1) return 0 ;;
    *) return 1 ;;
  esac
}

find_build_dir() {
  if [[ -n "${FNSERVE_BUILD_DIR}" && -x "${FNSERVE_BUILD_DIR}/validator-engine/validator-engine" ]]; then
    printf '%s\n' "${FNSERVE_BUILD_DIR}"
    return 0
  fi
  local candidate
  for candidate in "${REPO_ROOT}/build" "${REPO_ROOT}/build-debug" "${REPO_ROOT}/build-release" "${REPO_ROOT}/build-ton"; do
    if [[ -x "${candidate}/validator-engine/validator-engine" ]]; then
      printf '%s\n' "${candidate}"
      return 0
    fi
  done
  return 1
}

print_context() {
  log "repo_root=${REPO_ROOT}"
  log "branch=$(git -C "${REPO_ROOT}" rev-parse --abbrev-ref HEAD 2>/dev/null || true)"
  log "commit=$(git -C "${REPO_ROOT}" rev-parse HEAD 2>/dev/null || true)"
  log "mode=${FNSERVE_TOPOLOGY_MODE}"
  log "workdir=${FNSERVE_TOPOLOGY_WORKDIR}"
  log "master_host=${FNSERVE_MASTER_HOST}"
  log "master_port=${FNSERVE_MASTER_PORT}"
  log "disk_free=$(df -h "${FNSERVE_TOPOLOGY_WORKDIR}" | tail -n 1)"
}

check_tools() {
  local missing=0 tool
  for tool in git python3 timeout; do
    if ! command -v "$tool" >/dev/null 2>&1; then
      log "missing tool: ${tool}"
      missing=1
    else
      log "tool ${tool}: $(command -v "$tool")"
    fi
  done
  [[ "$missing" -eq 0 ]] || fail "required local tooling missing"
}

write_harness() {
  cat > "${HARNESS_FILE}" <<'PY'
#!/usr/bin/env python3
import asyncio
import os
import signal
import sys
from pathlib import Path

PUB_ED25519_PREFIX = bytes.fromhex("c6b41348")


def block_to_lite(block):
    shard = int(block.shard)
    if shard < 0:
        shard = (1 << 64) + shard
    return f"({int(block.workchain)},{shard:016x},{int(block.seqno)}):{bytes(block.root_hash).hex()}:{bytes(block.file_hash).hex()}"


def write_env(path: Path, values: dict[str, str]) -> None:
    tmp = path.with_suffix(path.suffix + ".tmp")
    with tmp.open("w", encoding="utf-8") as f:
        f.write("# Generated by audit/fnserve_master_01_topology/setup_local_fullnodemaster.sh\n")
        for key, value in values.items():
            escaped = value.replace("'", "'\\''")
            f.write(f"export {key}='{escaped}'\n")
    tmp.replace(path)


async def main() -> int:
    repo_root = Path(os.environ["FNSERVE_REPO_ROOT"]).resolve()
    build_dir = Path(os.environ["FNSERVE_BUILD_DIR"]).resolve()
    topology_dir = Path(os.environ["FNSERVE_TOPOLOGY_DIR"]).resolve()
    env_file = Path(os.environ["FNSERVE_ENV_FILE"]).resolve()
    master_port = int(os.environ["FNSERVE_MASTER_PORT"])
    max_seconds = int(os.environ.get("FNSERVE_TOPOLOGY_MAX_SECONDS", "900"))

    py_root = Path(os.environ["FNSERVE_PY_ROOT"]).resolve()
    sys.path.insert(0, str(py_root))
    sys.path.insert(0, str(repo_root / "test" / "tontester" / "src"))
    from tontester.install import Install
    from tontester.network import Network, StartOptions
    from tonapi import ton_api

    install = Install(build_dir, repo_root)
    topology_dir.mkdir(parents=True, exist_ok=True)

    stop = asyncio.Event()
    loop = asyncio.get_running_loop()
    for sig in (signal.SIGTERM, signal.SIGINT):
        try:
            loop.add_signal_handler(sig, stop.set)
        except NotImplementedError:
            pass

    async with Network(install, topology_dir, loop) as net:
        dht = net.create_dht_node()
        node = net.create_full_node()
        node.make_initial_validator()
        node.announce_to(dht)

        # Tontester does not expose full-node-master in its public constructor.
        # Mutate only this in-memory local test config before validator-engine writes
        # its copied config.json under the audit workdir.
        node._local_config.fullnodemasters = [
            ton_api.Engine_validator_fullNodeMaster(port=master_port, adnl=node.fullnode_key.id)
        ]

        await dht.run(StartOptions(threads=1, verbosity=3, console_verbosity=3))
        await node.run(StartOptions(threads=2, verbosity=3, console_verbosity=3))
        await net.wait_mc_block(1)
        client = await node.tonlib_client()
        mc_info = await client.get_masterchain_info()
        if mc_info.last is None:
            raise RuntimeError("tonlib returned no masterchain last block")

        zero_state = net.zerostate.as_block()
        env = {
            "FNSERVE_CONFIG": str(node._directory / "config.json"),
            "FNSERVE_MASTER_HOST": "127.0.0.1",
            "FNSERVE_MASTER_PORT": str(master_port),
            "FNSERVE_MASTER_PUBKEY_TL_HEX": (PUB_ED25519_PREFIX + node.fullnode_key.public_key.key).hex(),
            "FNSERVE_ZERO_STATE_BLOCK": block_to_lite(zero_state),
            "FNSERVE_BLOCK_ID": block_to_lite(mc_info.last),
            "FNSERVE_TARGET_PID": str(node._Node__process.pid),
            "FNSERVE_VALIDATOR_ENGINE": str(install.validator_engine_exe),
        }
        write_env(env_file, env)
        print("FORMAT FNSERVE_TOPOLOGY_READY", flush=True)
        for key, value in env.items():
            print(f"{key}={value}", flush=True)

        try:
            await asyncio.wait_for(stop.wait(), timeout=max_seconds)
        except asyncio.TimeoutError:
            print("FNSERVE_TOPOLOGY_TIMEOUT_STOP", flush=True)
    return 0


if __name__ == "__main__":
    raise SystemExit(asyncio.run(main()))
PY
  chmod +x "${HARNESS_FILE}"
}

ensure_tonapi() {
  log "ensuring repo-local tonapi Python bindings under ${TONAPI_DIR}"
  local out
  if ! out="$(python3 "${SCRIPT_DIR}/ensure_tonapi.py" --repo-root "${REPO_ROOT}" --output-root "${PY_ROOT}" 2>&1)"; then
    printf '%s\n' "${out}" > "${IMPORT_CHECK_LOG}"
    fail "failed to generate repo-local tonapi bindings; see ${IMPORT_CHECK_LOG}"
  fi
  printf '%s\n' "${out}" > "${IMPORT_CHECK_LOG}"
  PYTHONPATH="${PY_ROOT}:${REPO_ROOT}/test/tontester/src:${PYTHONPATH:-}" python3 - <<'PY' >> "${IMPORT_CHECK_LOG}" 2>&1 || fail "python import validation failed for tonapi/tontester; see ${IMPORT_CHECK_LOG}"
from tonapi import ton_api, tonlib_api
from tontester.install import Install
print("import_validation=ok")
PY
  log "tonapi_path=${TONAPI_DIR}"
}

start_topology() {
  is_private_host "${FNSERVE_MASTER_HOST}" || fail "refusing non-local master host ${FNSERVE_MASTER_HOST}"
  local build_dir
  build_dir="$(find_build_dir)" || fail "validator-engine build artifacts missing; expected validator-engine/validator-engine in FNSERVE_BUILD_DIR or common build dirs"
  [[ -d "${REPO_ROOT}/test/tontester/src" ]] || fail "repo-local tontester harness missing"
  [[ -f "${REPO_ROOT}/test/tontester/src/tontester/network.py" ]] || fail "tontester network.py missing"
  ensure_tonapi

  write_harness
  log "starting private tontester validator/fullnode topology; no PoC traffic is sent"
  (
    export FNSERVE_REPO_ROOT="${REPO_ROOT}"
    export FNSERVE_BUILD_DIR="${build_dir}"
    export FNSERVE_TOPOLOGY_DIR="${TOPOLOGY_DIR}"
    export FNSERVE_ENV_FILE="${ENV_FILE}"
    export FNSERVE_MASTER_PORT="${FNSERVE_MASTER_PORT}"
    export FNSERVE_TOPOLOGY_MAX_SECONDS="${FNSERVE_TOPOLOGY_MAX_SECONDS}"
    export FNSERVE_PY_ROOT="${PY_ROOT}"
    export PYTHONPATH="${PY_ROOT}:${REPO_ROOT}/test/tontester/src:${PYTHONPATH:-}"
    exec timeout --foreground "${FNSERVE_TOPOLOGY_MAX_SECONDS}" python3 "${HARNESS_FILE}"
  ) >"${LOG_DIR}/topology.log" 2>&1 &
  local harness_pid=$!
  printf '%s\n' "${harness_pid}" > "${PID_FILE}"

  local waited=0
  while [[ ${waited} -lt ${FNSERVE_TOPOLOGY_WAIT_SECONDS} ]]; do
    if [[ -s "${ENV_FILE}" ]]; then
      log "env_file=${ENV_FILE}"
      cat "${ENV_FILE}"
      printf 'FORMAT FNSERVE_TOPOLOGY_READY\n'
      printf 'exact files changed: audit/fnserve_master_01_topology/setup_local_fullnodemaster.sh, audit/fnserve_master_01_topology/ensure_tonapi.py, audit/fnserve_master_01_topology/extract_fullnodemaster_env.py, audit/fnserve_master_01_topology/README.md, audit/CODEX_LAST_STATUS.md\n'
      printf 'exact setup command: FNSERVE_TOPOLOGY_MODE=start FNSERVE_BUILD_DIR=%q bash audit/fnserve_master_01_topology/setup_local_fullnodemaster.sh\n' "${build_dir}"
      printf 'exact plan command: source %q && FNSERVE_MODE=plan bash audit/run_fnserve_master_01_local.sh\n' "${ENV_FILE}"
      printf 'exact generated/located tonapi path: %s\n' "${TONAPI_DIR}"
      printf 'exact variables generated: FNSERVE_CONFIG FNSERVE_MASTER_HOST FNSERVE_MASTER_PORT FNSERVE_MASTER_PUBKEY_TL_HEX FNSERVE_ZERO_STATE_BLOCK FNSERVE_BLOCK_ID FNSERVE_TARGET_PID FNSERVE_VALIDATOR_ENGINE\n'
      printf 'safety guarantees: 127.0.0.1 only, audit workdir only, repo-local generated tonapi only, timeout pid/log files, no public network, no PoC traffic, no git clean\n'
      printf 'what was not executed: no FNSERVE-MASTER-01 request traffic was sent\n'
      return 0
    fi
    if ! kill -0 "${harness_pid}" 2>/dev/null; then
      log "topology process exited early; log follows"
      tail -n 80 "${LOG_DIR}/topology.log" || true
      fail "private topology harness exited before producing FNSERVE env"
    fi
    sleep 1
    waited=$((waited + 1))
  done
  tail -n 80 "${LOG_DIR}/topology.log" || true
  fail "timed out waiting for private topology env file ${ENV_FILE}"
}

extract_or_reuse() {
  local config="${FNSERVE_CONFIG:-}"
  if [[ -z "${config}" ]]; then
    fail "FNSERVE_CONFIG not set for reuse/extract mode and no started topology env is available"
  fi
  python3 "${SCRIPT_DIR}/extract_fullnodemaster_env.py" \
    --config "${config}" \
    --output-env "${ENV_FILE}" \
    --workdir "${FNSERVE_TOPOLOGY_WORKDIR}" \
    --host "${FNSERVE_MASTER_HOST}" \
    --validator-engine "${FNSERVE_VALIDATOR_ENGINE:-}" \
    --target-pid "${FNSERVE_TARGET_PID:-}" \
    --zero-state-block "${FNSERVE_ZERO_STATE_BLOCK:-}" \
    --block-id "${FNSERVE_BLOCK_ID:-}"
}

plan() {
  cat <<PLAN
FORMAT FNSERVE_TOPOLOGY_READY
exact files changed: audit/fnserve_master_01_topology/setup_local_fullnodemaster.sh, audit/fnserve_master_01_topology/ensure_tonapi.py, audit/fnserve_master_01_topology/extract_fullnodemaster_env.py, audit/fnserve_master_01_topology/README.md, audit/CODEX_LAST_STATUS.md
exact setup command: FNSERVE_TOPOLOGY_MODE=start FNSERVE_BUILD_DIR=<repo-build-dir> bash audit/fnserve_master_01_topology/setup_local_fullnodemaster.sh
exact plan command: source ${ENV_FILE} && FNSERVE_MODE=plan bash audit/run_fnserve_master_01_local.sh
exact generated/located tonapi path: ${TONAPI_DIR}
exact variables generated: FNSERVE_CONFIG FNSERVE_MASTER_HOST FNSERVE_MASTER_PORT FNSERVE_MASTER_PUBKEY_TL_HEX FNSERVE_ZERO_STATE_BLOCK FNSERVE_BLOCK_ID FNSERVE_TARGET_PID FNSERVE_VALIDATOR_ENGINE
safety guarantees: local/private 127.0.0.1 fullNodeMaster only; repo-local tonapi generated under ${TONAPI_DIR}; copied tontester config under ${FNSERVE_TOPOLOGY_WORKDIR}; strict timeout ${FNSERVE_TOPOLOGY_MAX_SECONDS}s; PID/log/env files under audit workdir; no public network; no PoC traffic; no git clean
what was not executed: topology start and request traffic are not executed in plan mode
PLAN
}

print_context
check_tools
case "${FNSERVE_TOPOLOGY_MODE}" in
  plan) plan ;;
  start) start_topology ;;
  reuse|extract) extract_or_reuse ;;
  *) fail "unknown FNSERVE_TOPOLOGY_MODE=${FNSERVE_TOPOLOGY_MODE}; expected plan, start, reuse, or extract" ;;
esac
